# Site settings
author: Robin Smith
subtitle: Full-stack web developer
title: Full-stack Web Developer
brand: Robin Smith
year: 2018
email: robin@rsmith.io
phone: +44 7481 919 740
cv: robin_smiths_cv.pdf
years_experience: 7
description: > # this means to ignore newlines until "baseurl:"
  Experienced full-stack web developer building custom web applications and integrations using the best
  frameworks and cloud technologies
baseurl: "" # the subpath of your site, e.g. /blog
url: https://www.rsmith.io   # with the https protocol
github: robinrob
twitter: rsmith_io
facebook: robin.smith.50364591
linkedin: rsmithio

# Build settings
redcarpet:
  extensions: ["tables"]
markdown: redcarpet
highlighter: rouge

# Allow /index route in place of /index.html etc
permalink: /blog/:title/
plugins: [jekyll-paginate]
paginate_path: "/blog/page/:num"
paginate: 8
# Excludes these files/folders from being included into Jekyll _site folder.
# Note that you can also name files with a leading underscore to exclude them e.g.: _README.md
exclude: [node_modules, gulpfile.js, README.md, package.json, Gemfile, Gemfile.lock]
post_dirs: false

