# Site settings
title: Robin Smith
subtitle: Freelance web and mobile developer - UK
brand: Robin Smith Software
email: robin@mrrobinsmith.com
description: > # this means to ignore newlines until "baseurl:"
  Robin Smith Freelance Web application development services
#baseurl: "/robinrob.github.io-dev" # the subpath of your site, e.g. /blog
url: "http://robinrob.github.io" # the base hostname & protocol for your site
github: robinrob
twitter:
facebook: robin.smith.50364591
linkedin: http://www.linkedin.com/in/rsmithio

# Build settings
markdown: kramdown
author: Robin Smith

# Allow /index route in place of /index.html etc
permalink: pretty

# Excludes these files/folders from being included into Jekyll _site folder.
exclude: [node_modules]