
# Site settings
title: Robin Smith - Freelance Developer
subtitle: Freelance web and mobile developer - UK
brand: Robin Smith IO
email: rs@rsmith.io
description: > # this means to ignore newlines until "baseurl:"
  Experienced freelance software developer designing and building custom web applications and integrations using modern
  cloud technologies and frameworks.
#baseurl: "/robinrob.github.io-dev" # the subpath of your site, e.g. /blog
url: "https://rsmith.io" # the base hostname & protocol for your site
github: robinrob
twitter: rsmith_io
linkedin: rsmithio

# Build settings
markdown: kramdown
author: Robin Smith

# Allow /index route in place of /index.html etc
permalink: pretty

# Excludes these files/folders from being included into Jekyll _site folder.
exclude: [node_modules, gulpfile.js, README.md, package.json, Gemfile, Gemfile.lock]

url: https://rsmith.io   # with the https protocol
enforce_ssl: rsmith.io   # without any protocol