# Site settings
author: Robin Smith
subtitle: Freelance full-stack web developer
title: Robin Smith - Freelance Web Developer
brand: Robin Smith
email: robin@rsmith.io
description: > # this means to ignore newlines until "baseurl:"
  Experienced full-stack web developer building custom web applications and integrations using the best
  frameworks and cloud technologies.
baseurl: "" # the subpath of your site, e.g. /blog
url: https://rsmith.io   # with the https protocol
enforce_ssl: rsmith.io   # without any protocol
github: robinrob
twitter: rsmith_io
linkedin: rsmithio

# Build settings
markdown: redcarpet
highlighter: pygments
# Allow /index route in place of /index.html etc
permalink: /blog/:title

paginate_path: "/blog/page/:num"
paginate: 10
# Excludes these files/folders from being included into Jekyll _site folder.
# Note that you can also name files with a leading underscore to exclude them e.g.: _README.md
exclude: [node_modules, gulpfile.js, README.md, package.json, Gemfile, Gemfile.lock]
